management:
  server:
    port: 8080
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    health:
      show-components: always
      show-details: always
info:
  app:
    name: my-actuator
    version: 0.0.1-SNAPSHOT
logging:
  level:
    hello.controller: debug
